spring.application.name=EmailAssistant

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

#added the key in environment->run-<runconfiguration-springbootapp->environemnt add key and value for thsi project
gemini.api.key=${GEMINI_API_KEY}